Add Atmos by Cloud Posse
asdf-vm/asdf-plugins pull request #1042
Opened 2024-09-05 15:34 UTC by osterman

## Summary

Description:

- Tool repo URL: https://github.com/cloudposse/atmos
- Plugin repo URL: https://github.com/cloudposse/asdf-atmos

## Checklist

- [ ] Format with `scripts/format.bash`
- [ ] Test locally with `scripts/test_plugin.bash --file plugins/<your_new_plugin_name>`
- [ ] Your plugin CI tests are green
  - _Tip: use the `plugin_test` action from [asdf-actions](https://github.com/asdf-vm/actions) in your plugin CI_

2024-09-20 00:06 UTC, osterman commented
@jthegedus anything else we need to do to get this merged? Thanks!

2024-10-06 12:49 UTC, jthegedus approved these changes

2024-10-06 12:50 UTC, jthegedus commented
> @jthegedus anything else we need to do to get this merged? Thanks!

Nope, just a delay on my end. Thanks for your patience.

2024-10-06 12:52 UTC, jthegedus requested changes
Please rebase

2024-10-30 13:35 UTC, osterman commented
Thanks @jthegedus - fixed the conflict. I think there's some setting in our GHE preventing the ability for you to update it. Thanks for letting me know!

2025-03-16 15:12 UTC, jthegedus approved these changes
Sorry it took me so long to come back around to this. We encourage people to use the Git URL installation method anyway, so this shouldn't have caused too much of a disruption. Nonetheless, my bad 😅

2025-03-16 15:13 UTC, merged