feat: add has plugin
asdf-vm/asdf-plugins pull request #489
Opened 2021-10-03 22:25 UTC by sylvainmetayer

## Summary

## Checklist

- [x] CI tests are green. If you are using GitHub, you might want to use the `plugin_test` action from [asdf-actions](https://github.com/asdf-vm/actions)
- [ ] `asdf-plugins` CI sanity checks are green on your PullRequest. Test locally with:

```bash
./test_plugin.sh --file plugins/<PLUGIN_FILE>
```

2021-10-04 20:18 UTC, jthegedus requested changes
Please add this to the list in the readme

2021-10-05 08:08 UTC, sylvainmetayer commented
I edited my PR to include it to the README too

2021-10-05 09:36 UTC, jthegedus approved these changes

2021-10-05 09:36 UTC, jthegedus commented
thanks

2021-10-05 09:36 UTC, merged